"use client"
import * as React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./css/globals.css";
import Providers from "./providers";
import { createEmotionCache } from "../lib/createEmotionCache";
import { useServerInsertedHTML } from "next/navigation";
import createEmotionServer from "@emotion/server/create-instance";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // new cache per request (server-side)
  const cache = createEmotionCache();
  const { extractCriticalToChunks, constructStyleTagsFromChunks } =
    createEmotionServer(cache);

  useServerInsertedHTML(() => {
    const emotionChunks = extractCriticalToChunks(String(children));
    return (
      <style
        key="emotion-server-side"
        dangerouslySetInnerHTML={{
          __html: constructStyleTagsFromChunks(emotionChunks),
        }}
        data-emotion={`css ${emotionChunks.styles
          .map((s) => s.key)
          .join(" ")}`}
      />
    );
  });

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
